(* https://dune.readthedocs.io/en/stable/installation.html *)

(* run [ocaml ./add_share_dir.ml to generate share/dune]*)
open Printf;;

let () =
  let tmp = Filename.temp_file "share-" "" in
  let outfile = Filename.temp_file "dune-install-" "" in
  let ret = Sys.command ("find share > " ^ tmp) in
  if ret <> 0 then failwith "find error";
  let channel = open_in tmp in
  let out = open_out outfile in
  fprintf out "; autogenerated, don't edit\n";
  fprintf out "(install 
 (section share)
 (package goplot)
 (files";
  let rec loop () = try
      let line = input_line channel in
      (* for instance line = "share/images/axis.svg" *)
      
      if Sys.is_directory line || line.[0] = '.' ||
         line.[String.length line -1] = '~' ||
         String.sub (Filename.basename line) 0 4 = "dune"
      then begin
        print_endline  (sprintf "Skipping [%s]" line);
        loop ()
      end
      else begin
        let line = String.sub line 6 (String.length line - 6) in
      (* we remove the "share/" part. *)
        print_endline  (sprintf "file=[%s]" line);
        fprintf out "  (\"%s\" as \"%s\")\n" line line; 
        loop ()
      end
    with End_of_file -> close_in channel in
  loop ();
  fprintf out "))\n";
  close_out out;
  let ret = Sys.command (sprintf "cp %s share/dune" outfile) in
  if ret = 0 then print_endline "OK, share/dune generated"
  else print_endline "ERROR"

